App_Event/urls.py
from django.urls import path
from App_Event import views

app_name = 'App_Event'

urlpatterns = [
    path('<pk>/init/', views.EventInit.as_view(), name='initialize'),
    path('<pk>/subevent/<int:subevent>/config/', views.SubeventConfig.as_view(), name='config'),
    path('subevent/open/', views.OpenRegistration.as_view(), name='open'),
    path('subevent/<pk>/reg-toggle/', views.AllowSubeventRegistrationToggle.as_view(), name='allow_reg_toggle'),
    path('subevent/<pk>/review/', views.SubeventReview.as_view(), name='sub_review'),
    path('subevent/<int:pk>/review/<str:tab>/', views.SubeventReview.as_view(), name='sub_review_tab'),
    path('subevent/<pk>/reg/', views.RegisterToggle.as_view(), name='reg_toggle'),
    path('add-subevent/', views.AddSubevent.as_view(), name='add_subevent'),
    path('subevent/<pk>/finalize/', views.FinalizeSubeventStart.as_view(), name='sub_finalize'),
    path('get-rank-structure', views.GetRankStructure.as_view(), name='get_rank_structure'),
    path('subevent/<int:pk>/<int:rank_set>/process/', views.ProcessRanking.as_view(), name='process'),
]

App_Game/urls.py
from django.urls import path
from App_Game import views

app_name = 'App_Game'

urlpatterns = [
    path('create/', views.CreateGame.as_view(), name='create'),
    path('<pk>/start/', views.StartGame.as_view(), name='start'),
    path('<pk>/choose-your-seat/', views.GameSeatAssign.as_view(), name='choose_seat'),
    path('get-open-seats/', views.GetOpenSeats.as_view(), name='get_seats'),
    path('reserve-seat/', views.ReserveSeat.as_view(), name='reserve_seat'),
    path('unassign-seat/', views.ClearSeat.as_view(), name='unassign_seat'),
    path('move-seat/', views.MoveSeat.as_view(), name='move_seat'),
    path('game-section/<pk>/', views.GameSectionView.as_view(), name='game_section'),
    path('seat/<pk>/resolve/', views.ResolveGameSeat.as_view(), name='resolve_seat'),
    path('section/<pk>/resolve/', views.ResolveGameEquip.as_view(), name='resolve_equip'),
]

App_Organization/urls.py
from django.urls import path
from App_Organization import views
from App_Invitation.views import start_invitation, user_invites
from App_Shop import views as ShopViews
from App_Event import views as EventViews


app_name = "App_Organization"

urlpatterns = [
    path("", views.home, name="home"),
    path(
        "success/",
        ShopViews.CheckoutSuccess.as_view(),
        name="checkout_success",
    ),
    path("cancel/", ShopViews.CheckoutCancel.as_view(), name="checkout_cancel"),
    # stripe auth
    path(
        "authorize/<uuid>/",
        views.StripeAuthorizeView.as_view(),
        name="authorize",
    ),
    path(
        "oauth/callback/",
        views.StripeAuthorizeCallbackView.as_view(),
        name="authorize_callback",
    ),
    path("webhooks/stripe/", ShopViews.stripe_webhook, name="stripe-webhook"),
    #
    path("my-events/", EventViews.UserEvents.as_view(), name="my_events"),
    path(
        "manage/<str:org_type>",
        views.ManageOrganizations.as_view(),
        name="my_organizations",
    ),
    # path to normalize viewing all invitations from organizations
    # ex. current_site/my-invites
    path("my-invites/", user_invites, name="my_invites"),
    path("approve/<pk>/", views.approve_application, name="approve"),
    path("reject/<pk>/", views.reject_application, name="reject"),
    path("archive/<pk>/", views.archive_application, name="archive"),
    path(
        "application/<str:org_type>",
        views.application_custom,
        name="application",
    ),
    path(
        "application/status/",
        views.application_status,
        name="application_status",
    ),
    path(
        "application/<pk>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path("<slug:slug>/", views.organization_view, name="organization"),
    path("<slug:slug>/follow/", views.follow, name="follow"),
    path("<slug:slug>/unfollow/", views.unfollow, name="unfollow"),
    path("<slug:slug>/staff/", views.organization_staff, name="staff"),
    path("<slug>/update/", views.edit_organization, name="edit_organization"),
    # path to normalize starting invitations from organizations
    # ex. current_site/league-slug/invite
    path("<slug>/invite/", start_invitation, name="invite"),
    # Products
    path(
        "<slug>/new-product/",
        ShopViews.NewProductView.as_view(),
        name="new_product",
    ),
    path(
        "<slug>/products/",
        ShopViews.ProductListView.as_view(),
        name="products",
    ),
    path(
        "<slug>/products/<pk>/",
        ShopViews.ProductDetail.as_view(),
        name="product_detail",
    ),
    # Events
    path("<slug>/new-event/", EventViews.NewEvent.as_view(), name="new_event"),
    path(
        "<slug>/new-event/<pk>/event-detail/",
        EventViews.NewEventDetail.as_view(),
        name="new_event_detail",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/",
        EventViews.BuildEventCart.as_view(),
        name="new_event_cart",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/add/",
        EventViews.AddToEventCart.as_view(),
        name="event_cart_add",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/remove/",
        EventViews.RemoveFromEventCart.as_view(),
        name="event_cart_remove",
    ),
    path(
        "<slug>/new-event/<pk>/review/",
        EventViews.EventReview.as_view(),
        name="event_review",
    ),
    path(
        "<slug>/new-event/<pk>/submit/",
        EventViews.EventFinalSubmit.as_view(),
        name="event_submit",
    ),
    path(
        "<slug>/event/<pk>/review/",
        EventViews.EventOrgReview.as_view(),
        name="event_org_review",
    ),
    path(
        "<slug>/event/<pk>/approve/",
        EventViews.EventApprove.as_view(),
        name="event_approve",
    ),
    path(
        "<pk>/payment/",
        ShopViews.GetPaymentIntent.as_view(),
        name="payment_intent",
    ),
    path(
        "<slug:slug>/event/<int:event>/cart/<int:cart>/checkout/",
        ShopViews.CartPayment.as_view(),
        name="cart_payment",
    ),
    path(
        "<pk>/invoice/",
        ShopViews.CreateInvoice.as_view(),
        name="create_invoice",
    ),
    path(
        "<slug>/event/<pk>/staff-toggle/",
        EventViews.EventStaffRegToggle.as_view(),
        name="staff_toggle",
    ),
    path(
        "<slug>/event-staff/<pk>/add/",
        EventViews.StaffEventRegAdd.as_view(),
        name="staff_add",
    ),
]

LeagueBox/urls.py
import App_Event
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('App_Organization.urls')),
    path('invitation/', include('App_Invitation.urls')),
    path('posts/', include('App_Post.urls')),
    path('products/', include('App_Shop.urls')),
    path('events/', include('App_Event.urls')),
    path('games/', include('App_Game.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Event/models.py
from datetime import timedelta
from django.utils import timezone
from django.db import models
from django.conf import settings


from phone_field import PhoneField
from localflavor.us.models import USZipCodeField, USStateField

from App_Organization.models import Organization


class Event(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='event_user')
    user_org = models.ForeignKey(Organization, on_delete=models.DO_NOTHING, related_name='event_user_org', blank=True, null=True, help_text='Pick the organization hosting the event.')
    organization = models.ForeignKey(Organization, on_delete=models.DO_NOTHING, related_name='event_org')
    created = models.DateTimeField(auto_now_add=True)
    start = models.DateTimeField(help_text='Pick your event date and time. Required.')
    end = models.DateTimeField(blank=True, null=True, help_text='Specific end date/time for your event. Not required.')
    submitted = models.BooleanField(default=False)
    submitted_date = models.DateTimeField(blank=True, null=True)
    approved = models.BooleanField(default=False)
    approved_date = models.DateTimeField(blank=True, null=True)
    initialized = models.BooleanField(default=False)
    initialized_date = models.DateTimeField(blank=True, null=True)
    fulfilled = models.BooleanField(default=False)
    fulfilled_date = models.DateTimeField(blank=True, null=True)
    allow_staff_registration = models.BooleanField(default=False)

    def __str__(self):
        return f'{str(self.start)} | {self.organization.organization_name} | {self.user.email}'

    @property
    def is_expired(self):
        if self.initialized or self.fulfilled:
            return False
        expires_date = timezone.localtime(self.start).date() + timedelta(days=1)
        return timezone.localtime(timezone.now()).date() >= expires_date


class EventDetail(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, related_name='detail')
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=30)
    state = USStateField()
    postal_code = USZipCodeField()
    phone = PhoneField(help_text='Event Contact Phone Number')
    requests = models.CharField(max_length=512, blank=True, null=True)

    def __str__(self):
        return f'{str(self.event.start)} | {self.event.organization.organization_name} | {self.event.user.email}'


class EventStaff(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='event_staff_event')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name='event_staff_user')
    product = models.ForeignKey('App_Shop.Product', on_delete=models.CASCADE, related_name='event_staff_product')

    class Meta:
        verbose_name_plural = "Event Staff"

    def __str__(self):
        staff_name = 'Not Assigned'
        event_datetime = self.event.start.strftime("%d%b%Y %H:%M")
        if self.user:
            staff_name = self.user.profile.get_profile_firstlast()
        return f'{event_datetime} | {self.event.user_org} | {self.product.name} | {staff_name}'

    def get_role(self):
        return self.product.role


class SubEventType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Subevent Type"
        verbose_name_plural = "Subevent Types"

    def __str__(self):
        return self.name


STATUS_CHOICES = (('init', 'Init'), ('open', 'Open'), ('closed', 'Closed'))


class SubEvent(models.Model):
    event = models.ForeignKey(Event, on_delete=models.DO_NOTHING, related_name='subevents')
    type = models.ForeignKey(SubEventType, on_delete=models.DO_NOTHING, related_name='subevent_type')
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        null=True,
        blank=True,
    )
    allow_coin_boost = models.BooleanField(default=False)
    finalized = models.BooleanField(default=False)
    finalized_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.type} {self.event.id}'

    @property
    def allow_reg(self):
        if self.status == 'open':
            return True

    @property
    def needs_config(self):
        if self.status == 'init':
            return True


class SubEventRegistration(models.Model):
    subevent = models.ForeignKey(SubEvent, on_delete=models.DO_NOTHING, related_name='subevent_reg')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='subevent_user')
    coin_boost = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)
    closed_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = "Subevent Registration"
        verbose_name_plural = "Subevent Registrations"
        unique_together = ('subevent', 'user')
        ordering = ['subevent', 'created_date']

    def __str__(self):
        return f'{self.subevent.type} | {self.subevent.event.id} | {self.user.profile.display_name}'

App_Event/forms.py
import datetime
from django import forms
from django.db.models import Q
from bootstrap_datepicker_plus import DateTimePickerInput

from App_Event.models import Event, EventDetail

from App_Organization.models import Organization

from App_Game.models import GameType

from App_Equipment.models import Equipment


class NewEventForm(forms.ModelForm):

    recurring = forms.BooleanField(label='Weekly Recurring Event', required=False, help_text='Select if you would like to have a weekly recurring event.')

    class Meta:
        model = Event
        fields = ['user_org', 'start', 'end', ]
        widgets = {
            'start': DateTimePickerInput(
                options={
                    'minDate': (datetime.datetime.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d 00:00:00'),
                    'enabledHours': [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ],
                },
            ),
            'end': DateTimePickerInput(
                options={
                    'minDate': (datetime.datetime.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d 00:00:00'),
                }
            )
        }

    def __init__(self, *args, **kwargs):
        self.organization = kwargs.pop('organization', None)
        self.user = kwargs.pop('user', None)
        super(NewEventForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['user_org'].queryset = Organization.objects.filter(~Q(staff_organization__organization=self.organization), staff_organization__user=self.user, orgtype__orgtype='Venue')
            self.fields['user_org'].label = 'Hosting Organization'
            self.fields['user_org'].empty_label = 'User Hosted'
            self.fields['start'].label = 'Start Date'
            self.fields['end'].label = 'End Date'


class NewEventDetailForm(forms.ModelForm):
    requests = forms.CharField(
        required=False,
        widget=forms.Textarea()
    )

    class Meta:
        model = EventDetail
        exclude = ['event', ]

    def __init__(self, *args, **kwargs):
        self.organization = kwargs.pop('user_org', None)
        self.event = kwargs.pop('event', None)
        super(NewEventDetailForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['requests'].label = 'Additional Requests or Information'
            if EventDetail.objects.filter(event=self.event).exists():
                self.event_detail = EventDetail.objects.get(event=self.event)
                self.fields['address_1'].initial = self.event_detail.address_1
                self.fields['address_2'].initial = self.event_detail.address_2
                self.fields['city'].initial = self.event_detail.city
                self.fields['state'].initial = self.event_detail.state
                self.fields['postal_code'].initial = self.event_detail.postal_code
                self.fields['phone'].initial = self.event_detail.phone
                self.fields['requests'].initial = self.event_detail.requests
            else:
                if self.organization:
                    self.fields['address_1'].initial = self.organization.address_1
                    self.fields['address_2'].initial = self.organization.address_2
                    self.fields['city'].initial = self.organization.city
                    self.fields['state'].initial = self.organization.state
                    self.fields['postal_code'].initial = self.organization.postal_code
                    self.fields['phone'].initial = self.organization.phone


class SubeventConfigForm(forms.Form):

    create_game = forms.BooleanField(
        label="Create Game",
        help_text='Select if this subevent will require a game',
        widget=forms.CheckboxInput(
            attrs={'class': 'MyClass'}
        ),
        required=False,
    )

    game_type = forms.ModelChoiceField(
        queryset=GameType.objects.all(),
        required=False,
        label='Game Type:'
    )

    game_equipment = forms.ModelMultipleChoiceField(
        queryset=Equipment.objects.all(),
        required=False
    )

templates/App_Event/my_events.html
{% extends "base.html" %}
{% load event_custom_tags %}

{% block extrahead %}
{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}

{% for event in user_events %}
<div class="card mb-2 shadow">
    <div class="card-header">
        <div class="row">
            <div class="col-8">
                <small>
                <strong>Event Date: </strong>{{event.start}} <br>
                <strong>{{event.organization.orgtype.orgtype}}: </strong>{{event.organization}}
                </small>
            </div>
                {% if event.fulfilled %}
                <div class="col-4 alert alert-secondary">
                Fulfilled
                <div class="col-4 alert alert-success">
                Approved
                {% elif event.submitted %}
                <div class="col-4 alert alert-warning">
                Pending
                {% endif %}
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    {% if event.user_org %}
                    <span class="h5">{{event.user_org}}</span> <br>
                    {% endif %}
                    {{event.detail.address_1}} <br>
                    {% if event.detail.address_2%}
                        {{event.detail.address_2}} <br>
                    {% endif %}
                    {{event.detail.city}}, 
                    {{event.detail.state}} <br>
                    {{event.detail.postal_code}} <br>
                    {{event.detail.phone}} <br>
                </div>
                <div class="col-6">
                    {% for cart in event.event_cart.all %}
                        {% for item in cart.get_cart_items %}
                            {{item.product.name}} X {{item.quantity}} <br>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="row pt-2">
                    <div class="col-12">
                        Additional Requests:
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        {{event_details.requests}}
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
    
{% endfor %}

{% endblock %}

{% block script_block %}
{{block.super}}
{% endblock %}

templates/App_Event/new_event_build_cart.html
{% extends "base.html" %}
{% load event_custom_tags %}
{% load crispy_forms_tags %}

{% block extrahead %}

{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
{% csrf_token %}
<div class="jumbotron jumbotron-fluid my-0" style="background:transparent !important">
    <h1 class="display-4">Add Event Services</h1>
    <p class="lead">Choose services for your event</p>
    <hr class="my-2">
    <span class="h6 text-muted align-middle">{{organization.organization_name}}</span>
    <span><i class="fa fa-chevron-right fa-1x align-bottom text-muted"></i></span>
    <span class="h6 align-middle text-muted">Event</span>
    <span><i class="fa fa-chevron-right fa-1x align-bottom text-muted"></i></span>
    <span class="h6 align-middle text-muted">Event Details</span>
    <span><i class="fa fa-chevron-right fa-1x align-bottom text-muted"></i></span>
    <span class="h6 align-middle font-weight-bold">Event Services</span>
</div>

<div class="row border-bottom">
    <div class="col-2"></div>
    <div class="col-4 font-weight-bold">Name</div>
    <div class="col-2 font-weight-bold text-right">Price</div>
    <div class="col-1 font-weight-bold text-center">Qty</div>
    <div class="col-3"></div>
    
</div>
{% for product in products %}
<div class="row border-bottom py-2 align-items-center" id="row_{{product.id}}">
    <div class="col-2">
        {% with product.image_product.all|first as image %}
            {% if image %}
                <a href="{% url 'App_Organization:product_detail' product.organization.slug product.pk%}">
                    <img class="w-100" src="{{ image.thumbnail.url }}" alt="">
                </a>
            {% endif %}
        {% endwith %} 
    </div>
    <div class="col-4"><span class="h6">{{ product.name }}</span> 
    </div>
    <div class="col-2 text-right">${{ product.price }}<br><span style="font-size: 12px;">{{ product.unit }}</span></div>
    
    <div class="col-1">
        <span class="px-2" style="font-size: 18px;" id="qty_{{product.id}}">
            {{product|get_qty:event}}
        </span>
    </div>
    <div class="col-3 text-center">
        <button onclick="updateItem(product={{product.id}}, updateURL='{% url 'App_Organization:event_cart_remove' slug=organization.slug pk=event.pk %}')" class="btn btn-danger btn-sm" >
            <i class="fa fa-minus-square"></i>
        </button>&nbsp;
        <button onclick="updateItem(product={{product.id}}, updateURL='{% url 'App_Organization:event_cart_add' slug=organization.slug pk=event.pk %}')" class="btn btn-success btn-sm" >
            <i class="fa fa-plus-square"></i>
        </button>
    </div>

    
</div>
{% endfor %}
<div class="row pt-2">
    <div class="col-12 text-right">
        <div id="change-me">
            Total: <span class="font-weight-bold" id="cart-total">${{ cart_total|floatformat:2 }}</span>
        </div>
    </div>
</div>
<div class="row pt-2">
    <div class="col-6 text-left">
        <a href="{% url 'App_Organization:new_event_detail' slug=organization.slug pk=event.pk%}" class="btn btn-danger btn-sm">Back: Event Details</a>
    </div>
    <div class="col-6 text-right">
        <a href="{% url 'App_Organization:event_review' slug=organization.slug pk=event.pk%}" class="btn btn-success btn-sm">Next: Review Your Event</a>
    </div>
</div>
{% endblock %}

{% block script_block %}
{{block.super}}
<script>
function updateItem(product, updateURL) {
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var qty_text = $("#qty_"+product)
    var cart_total = $('#cart-total')
        $.ajax({
            url: updateURL,
            method: "POST",
            headers: {'X-CSRFToken': csrftoken},
            data: {
                'product_id': product
            },
            success: function (data) {
                console.log(data);
                qty_text.text(data['product_qty']);
                cart_total.text(data['cart_total'])

            }
         });
    };
</script>
{% endblock %}

templates/App_Event/new_event_dialog_detail.html
{% extends "base.html" %}

{%  load crispy_forms_tags %}

{% block extrahead %}

{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
<div class="jumbotron jumbotron-fluid my-0" style="background:transparent !important">
    <h1 class="display-4">Event Details</h1>
    <p class="lead">Enter or verify the venue information for the event.</p>
    <hr class="my-2">
    <span class="h6 text-muted align-middle">{{organization.organization_name}}</span>
    <span><i class="fa fa-chevron-right fa-1x align-bottom text-muted"></i></span>
    <span class="h6 align-middle text-muted">Event</span>
    <span><i class="fa fa-chevron-right fa-1x align-bottom text-muted"></i></span>
    <span class="h6 align-middle font-weight-bold">Event Details</span>
</div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="row">
            <div class="col-12 text-right">
                <input type="submit" name="submit" value="Next: Add Event Services" class="btn btn-success btn-sm"/>
            </div>
        </div>
    </form>
{% endblock %}

{% block script_block %}
{{block.super}}

{% endblock %}

templates/App_Event/subevent_config_start.html
{% extends "base.html" %}

{%  load crispy_forms_tags %}

{% block extrahead %}

{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
 
    <div class="jumbotron jumbotron-fluid my-0 py-2" style="background:transparent !important">
        <span class="display-4">Configure {{subevent.type}}</span>
        <p class="lead">Choose your options for this subevent and we'll open registration.</p>
        <hr class="my-2">
    </div>
    <div id="notification-error" class="alert alert-danger d-none"></div>
    <div id="notification-success" class="alert alert-success d-none"></div>
    <form id="form" action="{% url 'App_Game:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.create_game|as_crispy_field}}
        <input type="checkbox" name="allow_vip" id="allow_vip"> <label for="allow_vip">Allow VIP</label>&nbsp;&nbsp;
            <small><em>If checked, Users may spend coins to register with VIP flag.</em></small>
        <div class="mt-2" id="gameForm" class="" style="display: none;">
            {{form.game_type|as_crispy_field}}
            <br>
            <label>Select Equipment:</label><br>
                {% for item in equipment %}
                <input class="form-group" type="checkbox" name="game_equipment" id="game_equipment_{{item.id}}" value="{{item.id}}"> {{item}} <br>
                {% endfor %}
            <br>
            <input type="checkbox" name="auto_assign" id="auto_assign"> <label for="auto_assign">Auto Assign Seats</label>&nbsp;&nbsp;
            <small><em>Leave unchecked if you would like users to choose their seat.</em></small>
        </div>
        <div class="mt-3" id="submit">
            <button id="submit-btn" class="btn btn-primary" type="submit">Open Registration</button>
        </div>
    </form>
{% endblock %}

{% block script_block %}
{{ block.super }}
<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    
    $('#id_create_game').click(function(){
        // $('#gameForm').toggleClass('d-none');
        $('#gameForm').slideToggle(500)
    });
    
    $('#form').on('submit', function(e){
        e.preventDefault();
        $('#notification-error').text('')
        $('#notification-error').addClass('d-none')
        allowVip = $('#allow_vip').is(':checked')
        if ($('#id_create_game').prop("checked") === false) {
            ajaxUrl = "{% url 'App_Event:open' %}"
            data = {
                subevent: parseInt("{{subevent.id}}"),
                allowVip: allowVip,
            }
            open_registration(ajaxUrl, data)
        } else {
            console.log('Submitted with game!');
            if (formValid()){
                ajaxUrl = "{% url 'App_Game:create' %}"
                data = {
                subevent: parseInt("{{subevent.id}}"),
                allowVip: allowVip,
                gameTypeOption: validGameType,
                equipmentSelected: validEquipment,
                autoAssignSeats: autoAssignSeats
            }
                open_registration(ajaxUrl, data);
            }
            
        }

    });

    function formValid() {
        var gameType = $('#id_game_type option:selected').val()
        if ( gameType === "") {
            $('#notification-error').text('Please select a game type.')
            $('#notification-error').removeClass('d-none')
            return false
        } else{
            validGameType = gameType
        }
        
        var equipment = $('input[name="game_equipment"]:checked').map(function(){
                return parseInt($(this).val());
            }).get()
        if (equipment.length < 1) {
            $('#notification-error').text('Please select at least one piece of equipment.')
            $('#notification-error').removeClass('d-none')
            return false
        } else {
            validEquipment = equipment
        }
        autoAssignSeats = $('#auto_assign').is(':checked')
        console.log('Form is valid.')
        return true
    }

    function open_registration() {
        successURL = "{% url 'App_Organization:event_org_review' subevent.event.organization.slug subevent.event.pk %}"
        $.ajax({
            url: ajaxUrl,
            beforeSend: function () {
                $("#form :input").prop("disabled", true);
                $('#submit-btn').append(" <i class='fa fa-spinner fa-spin'></i>").attr("disabled", "");
            },
            type: "POST",
            headers: {'X-CSRFToken': csrftoken},
            data: data,
            success: function(json) {
                $('#notification-success').text('Game Created!');
                $('#notification-success').removeClass('d-none');
                nextPage(1500, successURL);
            },
            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText);
            },
        });
    }
</script>
{% endblock %}