App_Event/urls.py
from django.urls import path
from App_Event import views

app_name = 'App_Event'

urlpatterns = [
    path('<pk>/init/', views.EventInit.as_view(), name='initialize'),
    path('<pk>/subevent/<int:subevent>/config/', views.SubeventConfig.as_view(), name='config'),
    path('subevent/open/', views.OpenRegistration.as_view(), name='open'),
    path('subevent/<pk>/reg-toggle/', views.AllowSubeventRegistrationToggle.as_view(), name='allow_reg_toggle'),
    path('subevent/<pk>/review/', views.SubeventReview.as_view(), name='sub_review'),
    path('subevent/<int:pk>/review/<str:tab>/', views.SubeventReview.as_view(), name='sub_review_tab'),
    path('subevent/<pk>/reg/', views.RegisterToggle.as_view(), name='reg_toggle'),
    path('add-subevent/', views.AddSubevent.as_view(), name='add_subevent'),
    path('subevent/<pk>/finalize/', views.FinalizeSubeventStart.as_view(), name='sub_finalize'),
    path('get-rank-structure', views.GetRankStructure.as_view(), name='get_rank_structure'),
    path('subevent/<int:pk>/<int:rank_set>/process/', views.ProcessRanking.as_view(), name='process'),
]

App_Game/urls.py
from django.urls import path
from App_Game import views

app_name = 'App_Game'

urlpatterns = [
    path('create/', views.CreateGame.as_view(), name='create'),
    path('<pk>/start/', views.StartGame.as_view(), name='start'),
    path('<pk>/choose-your-seat/', views.GameSeatAssign.as_view(), name='choose_seat'),
    path('get-open-seats/', views.GetOpenSeats.as_view(), name='get_seats'),
    path('reserve-seat/', views.ReserveSeat.as_view(), name='reserve_seat'),
    path('unassign-seat/', views.ClearSeat.as_view(), name='unassign_seat'),
    path('move-seat/', views.MoveSeat.as_view(), name='move_seat'),
    path('game-section/<pk>/', views.GameSectionView.as_view(), name='game_section'),
    path('seat/<pk>/resolve/', views.ResolveGameSeat.as_view(), name='resolve_seat'),
    path('section/<pk>/resolve/', views.ResolveGameEquip.as_view(), name='resolve_equip'),
]

App_Organization/urls.py
from django.urls import path
from App_Organization import views
from App_Invitation.views import start_invitation, user_invites
from App_Shop import views as ShopViews
from App_Event import views as EventViews


app_name = "App_Organization"

urlpatterns = [
    path("", views.home, name="home"),
    path(
        "success/",
        ShopViews.CheckoutSuccess.as_view(),
        name="checkout_success",
    ),
    path("cancel/", ShopViews.CheckoutCancel.as_view(), name="checkout_cancel"),
    # stripe auth
    path(
        "authorize/<uuid>/",
        views.StripeAuthorizeView.as_view(),
        name="authorize",
    ),
    path(
        "oauth/callback/",
        views.StripeAuthorizeCallbackView.as_view(),
        name="authorize_callback",
    ),
    path("webhooks/stripe/", ShopViews.stripe_webhook, name="stripe-webhook"),
    #
    path("my-events/", EventViews.UserEvents.as_view(), name="my_events"),
    path(
        "manage/<str:org_type>",
        views.ManageOrganizations.as_view(),
        name="my_organizations",
    ),
    # path to normalize viewing all invitations from organizations
    # ex. current_site/my-invites
    path("my-invites/", user_invites, name="my_invites"),
    path("approve/<pk>/", views.approve_application, name="approve"),
    path("reject/<pk>/", views.reject_application, name="reject"),
    path("archive/<pk>/", views.archive_application, name="archive"),
    path(
        "application/<str:org_type>",
        views.application_custom,
        name="application",
    ),
    path(
        "application/status/",
        views.application_status,
        name="application_status",
    ),
    path(
        "application/<pk>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path("<slug:slug>/", views.organization_view, name="organization"),
    path("<slug:slug>/follow/", views.follow, name="follow"),
    path("<slug:slug>/unfollow/", views.unfollow, name="unfollow"),
    path("<slug:slug>/staff/", views.organization_staff, name="staff"),
    path("<slug>/update/", views.edit_organization, name="edit_organization"),
    # path to normalize starting invitations from organizations
    # ex. current_site/league-slug/invite
    path("<slug>/invite/", start_invitation, name="invite"),
    # Products
    path(
        "<slug>/new-product/",
        ShopViews.NewProductView.as_view(),
        name="new_product",
    ),
    path(
        "<slug>/products/",
        ShopViews.ProductListView.as_view(),
        name="products",
    ),
    path(
        "<slug>/products/<pk>/",
        ShopViews.ProductDetail.as_view(),
        name="product_detail",
    ),
    # Events
    path("<slug>/new-event/", EventViews.NewEvent.as_view(), name="new_event"),
    path(
        "<slug>/new-event/<pk>/event-detail/",
        EventViews.NewEventDetail.as_view(),
        name="new_event_detail",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/",
        EventViews.BuildEventCart.as_view(),
        name="new_event_cart",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/add/",
        EventViews.AddToEventCart.as_view(),
        name="event_cart_add",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/remove/",
        EventViews.RemoveFromEventCart.as_view(),
        name="event_cart_remove",
    ),
    path(
        "<slug>/new-event/<pk>/review/",
        EventViews.EventReview.as_view(),
        name="event_review",
    ),
    path(
        "<slug>/new-event/<pk>/submit/",
        EventViews.EventFinalSubmit.as_view(),
        name="event_submit",
    ),
    path(
        "<slug>/event/<pk>/review/",
        EventViews.EventOrgReview.as_view(),
        name="event_org_review",
    ),
    path(
        "<slug>/event/<pk>/approve/",
        EventViews.EventApprove.as_view(),
        name="event_approve",
    ),
    path(
        "<pk>/payment/",
        ShopViews.GetPaymentIntent.as_view(),
        name="payment_intent",
    ),
    path(
        "<slug:slug>/event/<int:event>/cart/<int:cart>/checkout/",
        ShopViews.CartPayment.as_view(),
        name="cart_payment",
    ),
    path(
        "<pk>/invoice/",
        ShopViews.CreateInvoice.as_view(),
        name="create_invoice",
    ),
    path(
        "<slug>/event/<pk>/staff-toggle/",
        EventViews.EventStaffRegToggle.as_view(),
        name="staff_toggle",
    ),
    path(
        "<slug>/event-staff/<pk>/add/",
        EventViews.StaffEventRegAdd.as_view(),
        name="staff_add",
    ),
]

LeagueBox/urls.py
import App_Event
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('App_Organization.urls')),
    path('invitation/', include('App_Invitation.urls')),
    path('posts/', include('App_Post.urls')),
    path('products/', include('App_Shop.urls')),
    path('events/', include('App_Event.urls')),
    path('games/', include('App_Game.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Game/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls.base import reverse
from django.views.generic.base import TemplateView, View
from django.contrib import messages
from django.utils import timezone
from App_Equipment.models import Equipment
from App_Game.models import GameEquip, GameRank, GameSeat, GameType, Game
from App_Event.models import SubEvent, SubEventRegistration

from App_Event.views import require_seat_assignment, IsEventStaffMixin


# Create your views here.


class CreateGame(View):
    '''Accept ajax request to create a game and populate GameEquip with seats'''
    def post(self, request):
        if request.is_ajax():
            json_data = request.POST
            game_type = GameType.objects.get(id=json_data['gameTypeOption'])
            subevent = get_object_or_404(SubEvent, id=json_data['subevent'])

            auto_assign_seats = False
            if json_data['autoAssignSeats'] == 'true':
                auto_assign_seats = True

            # create a new game
            new_game = Game.objects.create(
                subevent=subevent,
                game_type=game_type,
                auto_assign_seats=auto_assign_seats,
            )
            new_game.save()

            # set up each piece of equipment and add default_seats
            equip = Equipment.objects.filter(id__in=json_data.getlist('equipmentSelected[]'))
            seats_created = 0
            equip_label = 0
            for item in equip:
                thing = get_object_or_404(Equipment, id=item.id)
                new_game_equip = None
                new_game_equip = GameEquip.objects.create(
                    equip=thing,
                    game=new_game,
                    label=(equip_label+1)
                )
                new_game_equip.save()
                equip_label += 1
                for x in range(thing.product.default_seats):
                    new_game_seat = None
                    new_game_seat = GameSeat.objects.create(
                        game_equip=new_game_equip,
                        seat=(x+1),
                    )
                    new_game_seat.save()
                    seats_created += 1

            # open subevent for registration
            allow_vip = False
            if json_data['allowVip'] == 'true':
                allow_vip = True
            subevent.allow_coin_boost = allow_vip
            subevent.status = 'open'
            subevent.save()
        return JsonResponse({'status': 200, 'gameId': new_game.pk})
        # return JsonResponse({'status': 200})


class GameSeatAssign(LoginRequiredMixin, TemplateView):
    template_name = 'App_Game/choose_seat.html'

    def dispatch(self, request, *args, **kwargs):
        self.game = get_object_or_404(Game, pk=kwargs['pk'])
        subevent = SubEvent.objects.get(id=self.game.subevent.id)
        url = HttpResponseRedirect(reverse('App_Event:sub_review', kwargs={'pk': subevent.pk}))

        # If user has already been assigned a seat, redirect to subevent review
        open_seat, has_seat = require_seat_assignment(subevent, request.user)
        if not open_seat:
            messages.add_message(request, messages.ERROR, 'There are no seats currently available. Seats will be assigned as availability changes.')
            return url
        if has_seat:
            messages.add_message(request, messages.WARNING, 'You already have a seat assignment.')
            return url
        game_equip = GameEquip.objects.filter(game=self.game)

        # query for equipment with available seats
        # todo: replace with get_available_game_equipment()
        self.seats_qs = GameSeat.objects.filter(game_equip__in=game_equip, seat_user__isnull=True)
        self.available_seats_qs = self.seats_qs.values_list('game_equip', flat=True).distinct()
        if not self.available_seats_qs:
            messages.add_message(request, messages.ERROR, 'There are no available seats for this game. Please see event staff.')
            # return url
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {}
        context['page_title'] = 'Choose A Seat'
        context['game'] = self.game

        available_game_equip = GameEquip.objects.filter(id__in=self.available_seats_qs).order_by('label')
        context['game_equip'] = available_game_equip
        return context


class GetOpenSeats(View):
    '''Return open seats for a specific GameEquip'''
    def post(self, request):
        if request.is_ajax():
            json_data = request.POST
            if json_data['equipId']:
                game_equip = GameEquip.objects.get(id=json_data['equipId'])
                available_seats = GameSeat.objects.filter(game_equip=game_equip, seat_user__isnull=True).values_list('seat', flat=True)
                available_seats = list(available_seats)
                print(available_seats)
                return JsonResponse({'status': 200, 'seat_list': sorted(available_seats)})
            else:
                available_seats = []
                return JsonResponse({'status': 200, 'seat_list': available_seats})
        return JsonResponse({'status': 'false'}, status=500)


class ReserveSeat(View):
    '''Assigns requested seat to user'''
    def post(self, request):
        json_data = request.POST
        print(json_data)

        game = Game.objects.get(pk=json_data['gameId'])

        # check that user is registered for subevent
        if json_data['regId']:
            registration = SubEventRegistration.objects.filter(pk=json_data['regId'])
        else:
            registration = SubEventRegistration.objects.filter(subevent=game.subevent, user=request.user)
        if registration:
            registration = registration[0]
            game_equip = GameEquip.objects.filter(id=json_data['equipId'])
            game_seat = GameSeat.objects.filter(game_equip=game_equip[0], seat=json_data['seatId'])
            print(game_seat)
            if game_seat:
                game_seat = game_seat[0]
                # check that seat is actually available.
                if game_seat.seat_user is None:
                    game_seat.seat_user = registration
                    game_seat.save()
                    response_data = {}
                    response_data['status'] = 200
                    response_data['result'] = 'Seat Assigned Successfully'
                    return JsonResponse(response_data)
        return JsonResponse({'status': 'false'}, status=500)


def assign_seat(game_equip_id, seat, registration):
    if registration.closed:
        print('This registration is closed and cannot be assigned to a seat')
        return False
    game_equip = GameEquip.objects.filter(id=game_equip_id)
    game_seat = GameSeat.objects.filter(game_equip=game_equip[0], seat=seat)
    if game_seat:
        game_seat = game_seat[0]
        # check that seat is actually available.
        if game_seat.seat_user is None:
            game_seat.seat_user = registration
            game_seat.save()
            print(game_seat)
            return True


def clear_seat(game_seat, user):
    if game_seat.seat_user.user == user:
        game_seat.seat_user = None
        game_seat.save()
        return True


class MoveSeat(View):
    '''Moves user from one seat to another'''
    def post(self, request):
        json_data = request.POST
        print(json_data)

        # make sure new seat is not already reserved
        new_seat_check = GameSeat.objects.get(game_equip=json_data['equipId'], seat=json_data['seatId'])
        print(new_seat_check)
        if new_seat_check.seat_user is not None:
            return JsonResponse({'status': 'false'}, status=500)
        # get the old seat info
        game_seat = GameSeat.objects.get(id=json_data['userSeatId'])
        registration = game_seat.seat_user
        # remove the registration from the game seat
        game_seat.seat_user = None
        game_seat.save()

        if assign_seat(json_data['equipId'], json_data['seatId'], registration):
            return JsonResponse({'status': '200'}, status=200)
        return JsonResponse({'status': 'false'}, status=500)


class ClearSeat(View):
    def post(self, request):
        json_data = request.POST
        print(json_data)
        if json_data['seatId']:
            # clear seat user
            # check request comes from the current seat user
            game_seat = GameSeat.objects.get(pk=json_data['seatId'])
            print(game_seat)
            if game_seat.seat_user.user == request.user:
                if clear_seat(game_seat, request.user):
                    response_data = {}
                    response_data['status'] = 200
                    response_data['result'] = 'Seat Unassigned Successfully'
                    return JsonResponse(response_data, status=200)
            return JsonResponse({'status': 'false'}, status=500)
        else:
            return JsonResponse({'status': 'false'}, status=500)


def get_available_game_equip(game):
    game_equip = GameEquip.objects.filter(game=game).order_by('label')
    seats_qs = GameSeat.objects.filter(game_equip__in=game_equip, seat_user__isnull=True)
    available_seats_qs = seats_qs.values_list('game_equip', flat=True).distinct()
    available_game_equip = GameEquip.objects.filter(id__in=available_seats_qs).order_by('label')
    return available_game_equip


class GameSectionView(LoginRequiredMixin, TemplateView):
    '''Simple view to display users assigned to game seats within a game equip'''
    template_name = 'App_Game/game_section.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        game_section = get_object_or_404(GameEquip, pk=kwargs['pk'])
        context['game_section'] = game_section

templates/App_Game/choose_seat.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrahead %}

{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
    
    <div class="jumbotron jumbotron-fluid my-0 py-2" style="background:transparent !important">
        <span class="display-4">Seat Selection for {{game.subevent.type}}</span>
        <p class="lead">Choose your seat for this subevent.</p>
        <hr class="my-2">
    </div>
    <div id="notification-error" class="alert alert-danger d-none"></div>
    <div id="notification-success" class="alert alert-success d-none"></div>
    <form action="{% url 'App_Game:reserve_seat' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <label for="game_equips">Choose:</label><br>
                <select class="select form-control" name="game_equips" id="game_equips">
                    {% for equip in game_equip.all %}
                        <option value="{{equip.id}}">
                            {{equip.equip.product.name}}: {{equip.label}}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-6">
                <label for="seat_list">Seat:</label>
                <div id="seat_list_wrapper">
                    <select class="select form-control" name="seat_list" id="seat_list">
                    </select>
                </div>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12 text-right">
                <button class="btn btn-primary" id="submit" type="submit">Submit</button>
            </div>
        </div>
        
    </form>
{% endblock %}

{% block script_block %}
{{ block.super }}
<script src="{% static 'js/game.js' %}"></script>
<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    equipSelect = $('#game_equips option:selected').val()
    seatSelect = document.getElementById("seat_list")
    submitBtn = $('#submit')
    ajaxUrl = '{% url "App_Game:get_seats" %}'
    
    window.addEventListener('load', function () {
        equipSelect = $('#game_equips option:selected').val()
        getSeats(equipSelect, seatSelect, submitBtn, ajaxUrl);
    })

    $('#game_equips').on('change', function(){
        equipSelect = $('#game_equips option:selected').val()
        getSeats(equipSelect, seatSelect, submitBtn, ajaxUrl);
    });

    $('#submit').click(function(e){
        e.preventDefault();
        $("#game_equips").prop("disabled", true)
        $("#seat_list").prop("disabled", true)
        assignSeat();
    });

    function assignSeat() {
        $("#submit").attr("disabled", true)
        $('#submit').append(" <i class='fa fa-spinner fa-spin'></i>").attr("disabled", "");
        ajaxUrl = "{% url 'App_Game:reserve_seat'%}"
        successURL = "{% url 'App_Event:sub_review' game.subevent.pk %}"
        data = {
            equipId: $('#game_equips option:selected').val(),
            seatId: $('#seat_list option:selected').val(),
            gameId: parseInt("{{game.pk}}"),
        };
        $.ajax({
            url: ajaxUrl,
            type: "POST",
            headers: {'X-CSRFToken': csrftoken},
            data: data,
            success: function(json) {
                $('#notification-success').text('Seat assignment successful!');
                $('#notification-success').removeClass('d-none');
                nextPage(1500, successURL);
            },
            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText);
            },
        });
    }
</script>
{% endblock %}

templates/App_Game/game_section.html
{% extends "base.html" %}
{% load event_custom_tags %}
{% load static %}

{%  load crispy_forms_tags %}

{% block extrahead %}

{% endblock %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
<h5>
    <a href="{% url 'App_Organization:event_org_review' game_section.game.subevent.event.organization.slug game_section.game.subevent.event.pk %}">
        {{game_section.game.subevent.event.organization.organization_name}} Event #{{game_section.game.subevent.event.id}}
    </a> >
    <a href="{% url 'App_Event:sub_review' game_section.game.subevent.pk %}">
        {{game_section.game.subevent.type}}
    </a> > 
    {{game_section.equip.product.name}} #{{game_section.label}}
</h5>
<div class="card shadow mb-3">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" id="subevent-list" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#detail" role="tab" aria-controls="detail" aria-selected="true">Detail</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-md-6">
                <strong>Event Date: </strong>{{game_section.game.subevent.event.start|date:"M d Y, h:i"}}
            </div>
            <div class="col-md-6">
                <strong>Organization: </strong>{{game_section.game.subevent.event.organization}}
            </div>
        </div>
        <div class="tab-content">
            <div class="tab-pane active" id="detail" role="tabpanel" aria-labelledby="detail-tab">
                <div class="row border-bottom justify-content-between">
                    <div class="col-4 text-center">
                        <strong>Seat</strong>
                    </div>
                    <div class="col-8">
                        <strong>User</strong>
                    </div>
                </div>
                <form>
                    
                        {% for seat in game_section.game_seat.all|order_by:"seat" %}
                            <style>
                                .seatrow:not(:last-child) {
                                    border-bottom: 1px solid #dee2e6;
                                }
                            </style>
                            <div class="seatrow row justify-content-between" style="padding-top: .3em;">
                                <div class="col-4 my-auto text-center">
                                    <div class="custom-control custom-radio">
                                        {% if seat.seat_user %}
                                            {% if request.user|is_event_staff:game_section.game.subevent.event %}
                                                <input class="custom-control-input" type="radio" name="seat_number" id="seat_{{seat.id}}" value="{{seat.id}}">
                                                <label class="custom-control-label" for="seat_{{seat.id}}"></label>
                                            {% endif %}
                                                {{seat.seat}}
                                            {% if request.user|is_event_staff:game_section.game.subevent.event %}
                                                </label>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-8">
                                    <span {% if seat.seat_user %}id="seat_name_{{seat.id}}"{% endif %}>{{seat.seat_user.user.profile.get_profile_firstlast}}</span>
                                </div>
                            </div>
                        {% endfor %}
                </form>
            </div>
        </div>
    </div>
    <div class="card-footer">
        
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3 text-left">
                <div id="action-group" class="btn-group btn-group-toggle d-none" data-toggle="buttons">
                    <label id="labelMove" class="btn btn-secondary">
                    <input type="radio" name="actions" id="optionMove" value="optionMove" autocomplete="off">Move
                    </label>
                    <label id="labelOption" class="btn btn-danger">
                    <input type="radio" name="actions" id="optionResolve" value="optionResolve" autocomplete="off"> Resolve
                    </label> 
                </div>
            </div>
            <div class="col-sm-6 col-md-6 my-1">
                <div id="move_wrapper" class="d-none">
                <select class="select form-control" name="game_equips" id="game_equips">
                    {% for equip in game_equip.all %}
                        <option value="{{equip.id}}">
                            {{equip.equip.product.name}}: {{equip.label}}
                        </option>
                    {% endfor %}
                </select> 
                </div>
            </div>
            <div class="col-sm-6 col-md-3 my-1">
                <div id="seat_list_wrapper" class="d-none">
                    <select class="select form-control" name="seat_list" id="seat_list">
                    </select>
                </div>
            </div>
        </div>
        <div id="submit_wrapper" class="d-none">
            <div class="row mt-2">
                <div class="col-12 text-right">
                    <button id="submit-btn" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </div>
        {% if game_section.is_empty %}
        <div class="row">
            <div class="col-12 mx-auto my-auto">
                <a href="{% url 'App_Game:resolve_equip' game_section.pk %}" class="btn btn-danger w-100">Close {{game_section.equip.product.name}}</a>
            </div>
        </div>
    {% endif %}
    </div>
</div>
{% csrf_token %}
{% endblock %}

{% block script_block %}
{{block.super}}
{% if request.user|is_event_staff:game_section.game.subevent.event %}
<script src="{% static 'js/game.js' %}"></script>
<script>
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    
    $(':radio[name="seat_number"]').click(function() {
        userSeatId = $(this).val()
        console.log(userSeatId)
        $('#action-group').removeClass('d-none')
        $("input:radio[name='actions']").each(function(i) {
            this.checked = false;
        });
        $('#seat_list_wrapper').addClass('d-none')
        $('#submit_wrapper').addClass('d-none')
        $('#game_equips').addClass('d-none')
    });
    
    equipSelect = $('#game_equips option:selected').val();
    seatSelect = document.getElementById("seat_list")
    submitBtn = $('#submit_wrapper')
    ajaxUrl = '{% url "App_Game:get_seats" %}'

    // insert empty seat options on page load
    window.addEventListener('load', function () {
        // if game equipment is empty, skip ajax call to get seats
        if ($('#game_equips').has('option').length > 0) {
            getSeats(equipSelect, seatSelect, submitBtn, ajaxUrl);
        } else {
            $('#optionMove').addClass('d-none')
            $('#labelMove').addClass('d-none')
        }
    })
    
    $('#game_equips').on('change', function(){
        equipSelect = $('#game_equips option:selected').val()
        console.log(equipSelect)
        getSeats(equipSelect, seatSelect, submitBtn, ajaxUrl);
    });

    $('input:radio[name=actions]').click(function() {
        if ($('input:radio[name=actions]:checked').val() == 'optionMove'){
            if ($('#game_equips').has('option').length == 0) {
                console.log('Length is 0')
                $('#submit-btn').attr('disabled', true);
                $('#seat_list').addClass('d-none');
                $('#submit_wrapper').addClass('d-none')
            } else {
                $('#seat_list_wrapper').removeClass('d-none')
                $('#submit_wrapper').removeClass('d-none')
            }
            $('#move_wrapper').removeClass('d-none')
            console.log('Move checked')
        } else if ($('input:radio[name=actions]:checked').val() == 'optionResolve') {
            $('#move_wrapper').addClass('d-none')
            $('#seat_list_wrapper').addClass('d-none')
            $('#submit_wrapper').removeClass('d-none')
            $('#submit-btn').attr('disabled', false)
            console.log('Resolve checked')
        }
    });

    $('#submit-btn').click(function(e){
        if ($('input:radio[name=actions]:checked').val() == 'optionMove') {
            newSeatId = $('#seat_list option:selected').val()
            moveAjaxUrl = "{% url 'App_Game:move_seat' %}"
            submitButton = $('#submit-btn')
            moveSeat(userSeatId, equipSelect, newSeatId, submitButton, moveAjaxUrl)
        } else if ($('input:radio[name=actions]:checked').val() == 'optionResolve') {
            var url = "{% url 'App_Game:resolve_seat' 123 %}"
            var id = userSeatId
            window.location.href = url.replace('123', id)
        }

        console.log($('input:radio[name=actions]:checked').val())
    })
</script>
{% endif %}
{% endblock %}

templates/App_Game/seat_select.html
<div class="row">
        <div class="col-sm-6 col-md-6 my-1">
            <div id="move_wrapper" class="d-none">
                <select class="select form-control" name="game_equips" id="game_equips">
                    {% for equip in game_equip.all %}
                        <option value="{{equip.id}}">
                            {{equip.equip.product.name}}: {{equip.label}}
                        </option>
                    {% endfor %}
                </select> 
            </div>
        </div>
        <div class="col-sm-6 col-md-3 my-1">
            <div id="seat_list_wrapper" class="d-none">
                <select class="select form-control" name="seat_list" id="seat_list">
                </select>
            </div>
        </div>
    </div>
    <div id="submit_wrapper" class="d-none">
        <div class="row mt-2">
            <div class="col-12 text-right">
                <button id="submit-btn" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>