App_Game/urls.py
from django.urls import path
from App_Game import views

app_name = 'App_Game'

urlpatterns = [
    path('create/', views.CreateGame.as_view(), name='create'),
    path('<pk>/start/', views.StartGame.as_view(), name='start'),
    path('<pk>/choose-your-seat/', views.GameSeatAssign.as_view(), name='choose_seat'),
    path('get-open-seats/', views.GetOpenSeats.as_view(), name='get_seats'),
    path('reserve-seat/', views.ReserveSeat.as_view(), name='reserve_seat'),
    path('unassign-seat/', views.ClearSeat.as_view(), name='unassign_seat'),
    path('move-seat/', views.MoveSeat.as_view(), name='move_seat'),
    path('game-section/<pk>/', views.GameSectionView.as_view(), name='game_section'),
    path('seat/<pk>/resolve/', views.ResolveGameSeat.as_view(), name='resolve_seat'),
    path('section/<pk>/resolve/', views.ResolveGameEquip.as_view(), name='resolve_equip'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.AccountSignupView.as_view(), name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Organization/urls.py
from django.urls import path
from App_Organization import views
from App_Invitation.views import start_invitation, user_invites
from App_Shop import views as ShopViews
from App_Event import views as EventViews


app_name = "App_Organization"

urlpatterns = [
    path("", views.home, name="home"),
    path(
        "success/",
        ShopViews.CheckoutSuccess.as_view(),
        name="checkout_success",
    ),
    path("cancel/", ShopViews.CheckoutCancel.as_view(), name="checkout_cancel"),
    # stripe auth
    path(
        "authorize/<uuid>/",
        views.StripeAuthorizeView.as_view(),
        name="authorize",
    ),
    path(
        "oauth/callback/",
        views.StripeAuthorizeCallbackView.as_view(),
        name="authorize_callback",
    ),
    path("webhooks/stripe/", ShopViews.stripe_webhook, name="stripe-webhook"),
    #
    path("my-events/", EventViews.UserEvents.as_view(), name="my_events"),
    path(
        "manage/<str:org_type>",
        views.ManageOrganizations.as_view(),
        name="my_organizations",
    ),
    # path to normalize viewing all invitations from organizations
    # ex. current_site/my-invites
    path("my-invites/", user_invites, name="my_invites"),
    path("approve/<pk>/", views.approve_application, name="approve"),
    path("reject/<pk>/", views.reject_application, name="reject"),
    path("archive/<pk>/", views.archive_application, name="archive"),
    path(
        "application/<str:org_type>",
        views.application_custom,
        name="application",
    ),
    path(
        "application/status/",
        views.application_status,
        name="application_status",
    ),
    path(
        "application/<pk>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path("<slug:slug>/", views.organization_view, name="organization"),
    path("<slug:slug>/follow/", views.follow, name="follow"),
    path("<slug:slug>/unfollow/", views.unfollow, name="unfollow"),
    path("<slug:slug>/staff/", views.organization_staff, name="staff"),
    path("<slug>/update/", views.edit_organization, name="edit_organization"),
    # path to normalize starting invitations from organizations
    # ex. current_site/league-slug/invite
    path("<slug>/invite/", start_invitation, name="invite"),
    # Products
    path(
        "<slug>/new-product/",
        ShopViews.NewProductView.as_view(),
        name="new_product",
    ),
    path(
        "<slug>/products/",
        ShopViews.ProductListView.as_view(),
        name="products",
    ),
    path(
        "<slug>/products/<pk>/",
        ShopViews.ProductDetail.as_view(),
        name="product_detail",
    ),
    # Events
    path("<slug>/new-event/", EventViews.NewEvent.as_view(), name="new_event"),
    path(
        "<slug>/new-event/<pk>/event-detail/",
        EventViews.NewEventDetail.as_view(),
        name="new_event_detail",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/",
        EventViews.BuildEventCart.as_view(),
        name="new_event_cart",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/add/",
        EventViews.AddToEventCart.as_view(),
        name="event_cart_add",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/remove/",
        EventViews.RemoveFromEventCart.as_view(),
        name="event_cart_remove",
    ),
    path(
        "<slug>/new-event/<pk>/review/",
        EventViews.EventReview.as_view(),
        name="event_review",
    ),
    path(
        "<slug>/new-event/<pk>/submit/",
        EventViews.EventFinalSubmit.as_view(),
        name="event_submit",
    ),
    path(
        "<slug>/event/<pk>/review/",
        EventViews.EventOrgReview.as_view(),
        name="event_org_review",
    ),
    path(
        "<slug>/event/<pk>/approve/",
        EventViews.EventApprove.as_view(),
        name="event_approve",
    ),
    path(
        "<pk>/payment/",
        ShopViews.GetPaymentIntent.as_view(),
        name="payment_intent",
    ),
    path(
        "<slug:slug>/event/<int:event>/cart/<int:cart>/checkout/",
        ShopViews.CartPayment.as_view(),
        name="cart_payment",
    ),
    path(
        "<pk>/invoice/",
        ShopViews.CreateInvoice.as_view(),
        name="create_invoice",
    ),
    path(
        "<slug>/event/<pk>/staff-toggle/",
        EventViews.EventStaffRegToggle.as_view(),
        name="staff_toggle",
    ),
    path(
        "<slug>/event-staff/<pk>/add/",
        EventViews.StaffEventRegAdd.as_view(),
        name="staff_add",
    ),
]

App_Post/urls.py
from django.urls import path
from App_Post import views

app_name = 'App_Post'

urlpatterns = [
    path('like/<str:page>/<pk>/', views.liked, name='like'),
    path('unlike/<str:page>/<pk>/', views.unliked, name='unlike'),
    path('<pk>/', views.post_view, name='post'),
    path('toggle_hide/<str:page>/<postpk>/<pk>/', views.toggle_hide, name='toggle_hide'),
]

LeagueBox/urls.py
import App_Event
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('App_Organization.urls')),
    path('invitation/', include('App_Invitation.urls')),
    path('posts/', include('App_Post.urls')),
    path('products/', include('App_Shop.urls')),
    path('events/', include('App_Event.urls')),
    path('games/', include('App_Game.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Organization/models.py
import uuid
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from django.urls import reverse
from App_Login.models import User

from phone_field import PhoneField
from localflavor.us.models import USZipCodeField, USStateField


# Create your models here.


class OrgType(models.Model):
    orgtype = models.CharField(max_length=10)

    def __str__(self):
        return self.orgtype


class Organization(models.Model):
    orgtype = models.ForeignKey(OrgType, on_delete=models.CASCADE, related_name='org_type')
    slug = models.SlugField(max_length=255, unique='true')
    organization_name = models.CharField(max_length=80, unique=True, null=False)
    organization_image = models.ImageField(upload_to='organization_images/', null=True, blank=True)
    description = models.TextField(help_text='Description of offered services')
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=30)
    state = USStateField()
    postal_code = USZipCodeField()
    phone = PhoneField(help_text='Main Contact Phone Number')
    created = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['orgtype', 'organization_name']

    def __str__(self):
        return f'{self.organization_name}'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.organization_name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('organization', kwargs={'slug': self.slug})


class Application(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='application')
    orgtype = models.ForeignKey(OrgType, on_delete=models.CASCADE, related_name='app_orgtype')
    organization_name = models.CharField(max_length=80)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    address_1 = models.CharField(max_length=255)
    address_2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=30)
    state = USStateField()
    postal_code = USZipCodeField()
    phone = PhoneField(help_text='Main Contact Phone Number')
    service_description = models.TextField(help_text='Description of offered services')
    application_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    approved_date = models.DateTimeField(null=True, blank=True)
    archived = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    rejected_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{ self.user.profile.get_profile_firstlast()} | {self.organization_name} | Type: {self.orgtype.orgtype}'


class League(models.Model):
    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True)
    stripe_user_id = models.CharField(max_length=255, blank=True)
    stripe_access_token = models.CharField(max_length=255, blank=True)
    stripe_refresh_token = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f'{self.organization.organization_name}'


class Venue(models.Model):
    organization = models.OneToOneField(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.organization.organization_name}'


class Role(models.Model):
    role_type = models.ForeignKey(OrgType, on_delete=models.CASCADE, related_name='role_type')
    role = models.CharField(max_length=30)

    class Meta:
        unique_together = ['role', 'role_type']
        ordering = ['role_type']

    def __str__(self):
        return f'{self.role_type} {self.role}'


class Staff(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='staff_organization')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='staff_user')
    roles = models.ManyToManyField(Role)

    class Meta:
        ordering = ['organization']
        verbose_name_plural = 'Staff'
        unique_together = ['organization', 'user']

    def __str__(self):
        return f'{self.organization.organization_name} | {self.organization.orgtype} |{self.user.profile.get_profile_firstlast()}'


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follow_user')
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='follow_organization')

    class Meta:
        ordering = ['organization']
        unique_together = ['follower', 'organization']

    def __str__(self):
        return f'{self.follower.profile.get_profile_firstlast()} follows {self.organization.organization_name}'

App_Organization/forms.py
from django import forms
from App_Organization.models import Application, Organization, OrgType
from localflavor.us.forms import USZipCodeField


class ApplicationAdminForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = '__all__'


class OrganizationAdminForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = '__all__'


class ApplicationForm(forms.ModelForm):
    organization_name = forms.CharField(label='Organization Name')
    postal_code = USZipCodeField(widget=forms.TextInput(attrs={'placeholder': 'xxxxx or xxxxx-xxxx'}))

    class Meta:
        model = Application
        exclude = ['user', 'orgtype', 'application_date', 'approved', 'approved_date', 'archived']


class OrganizationEdit(forms.ModelForm):
    first_name = forms.CharField(label='Primary Contact First Name')
    last_name = forms.CharField(label='Primary Contact Last Name')
    postal_code = USZipCodeField(widget=forms.TextInput(attrs={'placeholder': 'xxxxx or xxxxx-xxxx'}))

    class Meta:
        model = Organization
        exclude = ['orgtype', 'slug', 'organization_name', 'created', 'update_date']

templates/App_Organization/application_detail.html
{% extends "base.html" %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
<div class="container">
    <div class="row mb-2">
        <div class="col-sm-8"><h4>Application Review Detail</h4></div>
        {% if application.approved %}
        <div class="col-sm-2 alert alert-success">Approved <br> {{ application.approved_date|date:"M d, Y"}}</div>
        <div class="col-sm-2"><a href="{% url 'App_Organization:archive' pk=application.pk %}"><button class="btn btn-secondary w-100">Archive</button></a></div>
        {% else %}
        <div class="col-sm-2"><a class="btn btn-success btn-sm" href="{% url 'App_Organization:approve' pk=application.pk %}">Approve</a></div>
        <div class="col-sm-2"><a class="btn btn-danger btn-sm" href="{% url 'App_Organization:reject' pk=application.pk %}">Reject</a></div>
        {% endif %}
    </div>
    <div class="row pt-2 mb-2 border-top">
        <div class="col-sm-6"><h6>Application Date:</h6></div>
        <div class="col-sm-6">{{ application.application_date }}</div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-6"><h6>Application Type:</h6></div>
        <div class="col-sm-6 font-weight-bold">{{ application.orgtype }}</div>
    </div>
    <div class="row mb-4 border-bottom">
        <div class="col-sm-6"><h6>Submitted By:</h6></div>
        <div class="col-sm-6">{{ application.user.profile.get_profile_firstlast }}</div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-4"><h6>Organization:</h6></div>
        <div class="col-sm-8">{{ application.organization_name }}</div>
    </div>
    <div class="row">
        <div class="col-sm-12"><h6>Address:</h6></div>
    </div>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">{{ application.address_1 }}</div>
    </div>
    <div class="row">
        {% if application.address_2 %}
        <div class="col-sm-1"></div>
        <div class="col-sm-11">{{ application.address_2 }}</div>
        {% endif %}
    </div>
    <div class="row mb-3">
        <div class="col-sm-1"></div>
        <div class="col-sm-4">{{ application.city }}</div>
        <div class="col-sm-2">{{ application.state }}</div>
        <div class="col-sm-5">{{ application.postal_code }}</div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-4"><h6>Contact Name:</h6></div>
        <div class="col-sm-8">{{ application.first_name }} {{ application.last_name }}</div>
    </div>
    <div class="row pb-2 mb-2 border-bottom">
        <div class="col-sm-4"><h6>Phone</h6></div>
        <div class="col-sm-8">{{ application.phone }}</div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-12"><h6>Service Description:</h6></div>
    </div>
    <div class="row mb-2">
        <div class="col-sm-12">{{application.service_description}}</div>
    </div>
</div>
{% endblock %}

templates/App_Organization/home.html
{% extends "base.html" %}
{% load org_custom_tags %}
{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
    <div class="row">
        <div class="col-12 col-md-5">
            <div class="card shadow">
                <div class="card-body">
                    {% if request.user.is_authenticated %}
                    <span class="circle">{{ user.profile.display_name|initials }}</span>
                    <span class="h6">@{{ user.profile.display_name }}</span>
                    <div class="mt-2">Welcome {{ request.user.profile.first_name }}!</div>
                    {% else %}
                    <div class="mt-2">You are not logged in.</div>
                    <div>Sign in <a href="{% url 'App_Login:login' %}">here</a>. Don't have an account? <a href="{% url 'App_Login:signup' %}">Sign up today!</a></div>
                    {% endif %}
                </div>
                <ul class="list-group list-group-flush">
                </ul>
            </div>
        </div>
        <div class="col-md-7 gedf-main">
            {% for post in posts %}
            <!--- \\\\\\\Post-->
            <div class="card gedf-card shadow" id="post_{{post.id}}">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="mr-2">
                                <a href="{% url 'App_Organization:organization' slug=post.organization.slug %}">
                                {% if organization.organization_image %}
                                    <img class="rounded-circle" src="{{ post.organization.organization_image.url }}" alt="" style="width: 40px; height: 40px;">
                                {% else %}
                                    <span class="circle">{{ post.organization.organization_name|initials }}</span>
                                    
                                {% endif %}
                                </a>
                            </div>
                            <div class="ml-2">
                                <a href="{% url 'App_Organization:organization' slug=post.organization.slug %}">
                                    <div class="h5 m-0">{{ post.organization.organization_name }}</div>
                                </a>
                                <!-- <div class="h7 text-muted">Miracles Lee Cross</div> -->
                            </div>
                        </div>
                        <div>
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-ellipsis-h"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                    <div class="h6 dropdown-header">Configuration</div>
                                    <a class="dropdown-item" href="#">Save</a>
                                    <a class="dropdown-item" href="#">Hide</a>
                                    <a class="dropdown-item" href="#">Report</a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="card-body">
                    <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i> {{ post.created|timesince }}</div>
                    {% if not post.event %}
                    <a class="card-link" href="{% url 'App_Post:post' pk=post.pk %}">
                    {% else %}
                    <a class="card-link" href="{% url 'App_Organization:event_org_review' post.event.organization.slug post.event.pk %}">
                    {% endif %}
                        <h5 class="card-title">
                            {% if not post.event %}
                                {{ post.title }}
                            {% else %}
                                {{ post.event.organization }}
                                {% if post.event.user_org %}
                                    <i class="fa fa-arrow-circle-right" aria-hidden="true"></i> {{ post.event.user_org }}: Event
                                {% else %}
                                    : Event
                                {% endif %}
                    {% endif %}
                            
                        </h5>
                    </a>

                    <p class="card-text">
                        {% if not post.event %}
                            {{ post.content }}
                        {% else %}
                            <strong>Event Date</strong>: {{post.event.start}} <br>
                            <p>
                                {% for cart in post.event.event_cart.all%}
                                    {% for item in cart.get_cart_items %}
                                        {{item.product.name}} x {{item.quantity}}
                                    {% endfor %}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </p>
                    <p>
                        {% for image in post.postimages.all %}
                        <img class="w-100" src="{{ image.image.url }}" alt="">
                        <div>{{ image.caption }}</div>
                        {% endfor %}
                    </p>
                </div>
                <div class="card-footer">
                    {% if post.pk in liked_post_list %}
                        <a href="{% url 'App_Post:unlike' page='home' pk=post.pk %}" class="card-link"><i class="fa fa-heart" style="font-size: 14px;"></i></a>
                    {% else %}
                        <a href="{% url 'App_Post:like' page='home' pk=post.pk %}" class="card-link"><i class="fa fa-heart-o" style="font-size: 14px;"></i></a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        {% if post.commenting %}
                            <!-- <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a> -->
                        {% endif %}
                    {% endif %}
                    <!-- <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a> -->
                </div>
            </div>
            <!-- Post /////-->
            {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}

templates/App_Organization/manage_organizations.html
{% extends "base.html" %}

{% block title %}
    {{ page_title }}
{% endblock %}

{% block body_block %}
    {% if organization_list %}
    <div class="row">
        <div class="col-12">
            {% for organization in organization_list %}
            <div class="card mb-2 shadow">
                <div class="card-header">
                    <div class="row">
                        <div class="col-6">
                            <h5>{{ organization.organization_name }}</h5>
                        </div>
                        <div class="col-6 text-right">
                            <a href="{% url 'App_Organization:edit_organization' slug=organization.slug %}" class="btn btn-secondary btn-sm"><i class="fa fa-gears"></i></a>
                        </div>
                    </div>
                </div>
                <div class="card-body p-1">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 border">
                                <strong>Events</strong>
                                {% for event in organization.event_org.all %}
                                
                                
                                <div class="row mb-1">
                                    <div class="col-8">
                                        {{event.user_org}} | {{event.start}}
                                    </div>
                                    <div class="col-4 text-right"><a href="{% url 'App_Organization:event_org_review' organization.slug event.pk %}" class="btn btn-secondary btn-sm">Review</a></div>
                                </div>
                                {% endfor %}
                                {% for event in organization.event_user_org.all %}
                                
                                
                                <div class="row mb-1">
                                    <div class="col-8">
                                        {{event.organization}} | {{event.start}}
                                    </div>
                                    <div class="col-4 text-right"><a href="{% url 'App_Organization:event_org_review' organization.slug event.pk %}" class="btn btn-secondary btn-sm">Review</a></div>
                                </div>
                                {% endfor %}

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 border">
                                <div class="row pt-1">
                                    <div class="col-12">
                                        <h6>{{ organization.orgtype }} Staff:</h6>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        {% for staff in organization.staff_organization.all %}
                                            <div class="row">
                                                <div class="col-12">
                                                    {{ staff.user.profile.get_profile_firstlast }}:
                                                </div>
                                            </div>
                                            {% for role in staff.roles.all %}
                                                <div class="row">
                                                    <div class="col-2"></div>
                                                    <div class="col-10">{{ role.role }}</div>
                                                </div>
                                            {% endfor %}
                                        {% endfor %}
                                    </div>
                                </div>    
                            </div>
                        </div>
                        
                            <div class="row pt-1">
                                <div class="col-4"></div>
                                <div class="col-4"></div>
                                <div class="col-4 text-right"><a class="btn btn-primary btn-sm" href="{% url 'App_Organization:invite' slug=organization.slug %}">Invite Staff</a></div>
                            </div>
                            {% if organization.league %}
                            <div class="row pt-2 mt-2 border-top">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-12">
                                            <span class="h6">Total Products and Services:</span>  {{ organization.product_org.count }}
                                        </div>
                                    </div>
                                    <div class="row border-bottom mb-1">
                                        <div class="col-2"></div>
                                        <div class="col-5 font-weight-bold">Name</div>
                                        <div class="col-3 font-weight-bold text-right">Price</div>
                                        <div class="col-2 font-weight-bold">Unit</div>
                                    </div>
                                    {% for product in organization.product_org.all|slice:":3" %}
                                    <div class="row border-bottom mb-1 align-items-center">
                                        <div class="col-2">
                                            {% with product.image_product.all|first as image %}
                                                {% if image %}
                                                    <a href="{% url 'App_Organization:product_detail' product.organization.slug product.pk%}">
                                                        <img class="w-100" src="{{ image.thumbnail.url }}" alt="">
                                                    </a>
                                                {% endif %}
                                            {% endwith %} 
                                        </div>
                                        <div class="col-5"><span class="h6">{{ product.name }}</span> 
                                            <br>{{ product.product_type }}
                                        </div>
                                        <div class="col-3 text-right">${{ product.price }}</div>
                                        <div class="col-2">{{ product.unit }}</div>
                                    </div>
                                    {% endfor %}
                                    <div class="row py-1">
                                        <div class="col-6">
                                            <a class="btn btn-danger btn-sm" href="{% url 'App_Organization:new_product' slug=organization.slug %}">Add New Product</a>
                                        </div>
                                        
                                        <div class="col-6 text-right">
                                            <a class="btn btn-primary btn-sm" href="{% url 'App_Organization:products' slug=organization.slug %}">View All Products</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        {% if organization.league %}
                            {% if organization.league.stripe_access_token %}
                            <div class="col-4"><i class="fa fa-check-square-o" aria-hidden="true"></i> <i class="fa fa-cc-stripe" aria-hidden="true"></i> Connected!</div>
                            {% else %}
                            <div class="col-4"><a href="{% url 'App_Organization:authorize' organization.league.uuid %}" class="btn btn-primary"><i class="fa fa-cc-stripe" aria-hidden="true"></i> Connect Stripe Account</a></div>
                            {% endif %}
                        {% endif %}
                        <div class="col-4"></div>
                        <div class="col-4 text-right"></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    {% endif %}
{% endblock %}