App_Game/urls.py
from django.urls import path
from App_Game import views

app_name = 'App_Game'

urlpatterns = [
    path('create/', views.CreateGame.as_view(), name='create'),
    path('<pk>/start/', views.StartGame.as_view(), name='start'),
    path('<pk>/choose-your-seat/', views.GameSeatAssign.as_view(), name='choose_seat'),
    path('get-open-seats/', views.GetOpenSeats.as_view(), name='get_seats'),
    path('reserve-seat/', views.ReserveSeat.as_view(), name='reserve_seat'),
    path('unassign-seat/', views.ClearSeat.as_view(), name='unassign_seat'),
    path('move-seat/', views.MoveSeat.as_view(), name='move_seat'),
    path('game-section/<pk>/', views.GameSectionView.as_view(), name='game_section'),
    path('seat/<pk>/resolve/', views.ResolveGameSeat.as_view(), name='resolve_seat'),
    path('section/<pk>/resolve/', views.ResolveGameEquip.as_view(), name='resolve_equip'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.AccountSignupView.as_view(), name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Organization/urls.py
from django.urls import path
from App_Organization import views
from App_Invitation.views import start_invitation, user_invites
from App_Shop import views as ShopViews
from App_Event import views as EventViews


app_name = "App_Organization"

urlpatterns = [
    path("", views.home, name="home"),
    path(
        "success/",
        ShopViews.CheckoutSuccess.as_view(),
        name="checkout_success",
    ),
    path("cancel/", ShopViews.CheckoutCancel.as_view(), name="checkout_cancel"),
    # stripe auth
    path(
        "authorize/<uuid>/",
        views.StripeAuthorizeView.as_view(),
        name="authorize",
    ),
    path(
        "oauth/callback/",
        views.StripeAuthorizeCallbackView.as_view(),
        name="authorize_callback",
    ),
    path("webhooks/stripe/", ShopViews.stripe_webhook, name="stripe-webhook"),
    #
    path("my-events/", EventViews.UserEvents.as_view(), name="my_events"),
    path(
        "manage/<str:org_type>",
        views.ManageOrganizations.as_view(),
        name="my_organizations",
    ),
    # path to normalize viewing all invitations from organizations
    # ex. current_site/my-invites
    path("my-invites/", user_invites, name="my_invites"),
    path("approve/<pk>/", views.approve_application, name="approve"),
    path("reject/<pk>/", views.reject_application, name="reject"),
    path("archive/<pk>/", views.archive_application, name="archive"),
    path(
        "application/<str:org_type>",
        views.application_custom,
        name="application",
    ),
    path(
        "application/status/",
        views.application_status,
        name="application_status",
    ),
    path(
        "application/<pk>/",
        views.ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path("<slug:slug>/", views.organization_view, name="organization"),
    path("<slug:slug>/follow/", views.follow, name="follow"),
    path("<slug:slug>/unfollow/", views.unfollow, name="unfollow"),
    path("<slug:slug>/staff/", views.organization_staff, name="staff"),
    path("<slug>/update/", views.edit_organization, name="edit_organization"),
    # path to normalize starting invitations from organizations
    # ex. current_site/league-slug/invite
    path("<slug>/invite/", start_invitation, name="invite"),
    # Products
    path(
        "<slug>/new-product/",
        ShopViews.NewProductView.as_view(),
        name="new_product",
    ),
    path(
        "<slug>/products/",
        ShopViews.ProductListView.as_view(),
        name="products",
    ),
    path(
        "<slug>/products/<pk>/",
        ShopViews.ProductDetail.as_view(),
        name="product_detail",
    ),
    # Events
    path("<slug>/new-event/", EventViews.NewEvent.as_view(), name="new_event"),
    path(
        "<slug>/new-event/<pk>/event-detail/",
        EventViews.NewEventDetail.as_view(),
        name="new_event_detail",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/",
        EventViews.BuildEventCart.as_view(),
        name="new_event_cart",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/add/",
        EventViews.AddToEventCart.as_view(),
        name="event_cart_add",
    ),
    path(
        "<slug>/new-event/<pk>/event-cart/remove/",
        EventViews.RemoveFromEventCart.as_view(),
        name="event_cart_remove",
    ),
    path(
        "<slug>/new-event/<pk>/review/",
        EventViews.EventReview.as_view(),
        name="event_review",
    ),
    path(
        "<slug>/new-event/<pk>/submit/",
        EventViews.EventFinalSubmit.as_view(),
        name="event_submit",
    ),
    path(
        "<slug>/event/<pk>/review/",
        EventViews.EventOrgReview.as_view(),
        name="event_org_review",
    ),
    path(
        "<slug>/event/<pk>/approve/",
        EventViews.EventApprove.as_view(),
        name="event_approve",
    ),
    path(
        "<pk>/payment/",
        ShopViews.GetPaymentIntent.as_view(),
        name="payment_intent",
    ),
    path(
        "<slug:slug>/event/<int:event>/cart/<int:cart>/checkout/",
        ShopViews.CartPayment.as_view(),
        name="cart_payment",
    ),
    path(
        "<pk>/invoice/",
        ShopViews.CreateInvoice.as_view(),
        name="create_invoice",
    ),
    path(
        "<slug>/event/<pk>/staff-toggle/",
        EventViews.EventStaffRegToggle.as_view(),
        name="staff_toggle",
    ),
    path(
        "<slug>/event-staff/<pk>/add/",
        EventViews.StaffEventRegAdd.as_view(),
        name="staff_add",
    ),
]

LeagueBox/urls.py
import App_Event
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('App_Organization.urls')),
    path('invitation/', include('App_Invitation.urls')),
    path('posts/', include('App_Post.urls')),
    path('products/', include('App_Shop.urls')),
    path('events/', include('App_Event.urls')),
    path('games/', include('App_Game.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> -->

    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extrahead %}
    {% endblock %}
    {% block css_block %}
    {% endblock %}
</head>
<body>

{% include "navbar.html"%}
{% include "header.html" %}
    <main id="main">


        <div class="container" style="padding-top: 20px;">


        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}
                <div {% if message.tags%} class="alert alert-{{ message.tags }} {% endif %}" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-level="Close"><span aria-hidden="true"> &times; </span></button>
                </div>
                {% endfor %}
            {% endif %}
        </div>

        {% block body_block  %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block extra_body %}
        {% endblock %}

        </div>
    </main>
    {% include "footer.html" %}

    {% block script_block %}
{{block.super}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script>
        function openNav() {
          document.getElementById("myNav").style.width = "100%";
        }

        function closeNav() {
          document.getElementById("myNav").style.width = "0%";
        }
        </script>
    {% endblock %}
</body>
</html>

templates/footer.html
<footer class="fixed-bottom bg-dark" style="margin-bottom: 0px;"> 
    <div class="container text-white">
        <div class="row pt-3 pb-3">
            <div class="col-6">
                <h6 class="mb-0 pb-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp; Have your own league?</h6>
                <div class="row">
                    <div class="col-12">
                        <a class="text-decoration-none text-white" style="font-size: 0.8rem;" href="{% url 'App_Organization:application' org_type='League' %}">Register Your League</a><br>
                        <a class="text-decoration-none text-white" style="font-size: 0.8rem;" href="{% url 'App_Organization:application_status' %}">Check Application Status</a>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <a class="text-decoration-none text-white" href="#">Some Link</a>
            </div>
        </div>
    </div>
</footer>

templates/header.html
<div id="myNav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="overlay-content">
      {% if not user.is_authenticated %}
      <a href="{% url 'App_Login:login' %}">Sign In</a>
      {% endif %}
      <a href="{% url 'account_logout' %}">Sign Out</a>
      <a href="{% url 'App_Organization:my_organizations' org_type='League' %}">My Leagues</a>
      <a href="{% url 'App_Organization:my_organizations' org_type='Venue' %}">My Venues</a>
      <a href="{% url 'account_logout' %}">My Events</a>
    </div>
</div>

templates/landing.html
{% extends "m_base.html" %}
{% load static %}

    {% block body_block  %}
    <!-- Section: Carousel -->
    <style>
        #carousel-1 {
            background-image: url('{% static "images/LB_landing2.jpg" %}');
        }
        #carousel-2 {
            background-image: url('{% static "images/LB_landing5.jpg" %}');
        }
        #carousel-3 {
            background-image: url('{% static "images/LB_landing3.jpg" %}');
        }
        #carousel-4 {
            background-image: url('{% static "images/LB_landing4.jpg" %}');
        }
    </style>
    <div class="carousel carousel-slider">

        <div class="carousel-fixed-item center clearfix">
            <a id="fixedCarouselButton" class="btn btn-large waves-effect waves-light deep-orange z-depth-3">Learn More</a>
        </div>

          <div id="carousel-1" class="carousel-item white-text" href="#one!">
            <div class="primary-overlay">
                <div class="container center">
                    <h3 class="carousel-head">Welcome To LeagueBox!</h3>
                    <p class="white-text">LeagueBox is a platform that brings Leagues, Venues, and Members together</p>
                </div>
            </div>
          </div>
          <div id="carousel-2" class="carousel-item white-text" href="#Leagues">
            <div class="primary-overlay">
                <div class="container">
                    <h3 class="carousel-head">Second Panel</h3>
                    <p class="white-text">This is your third panel</p>
                </div>
            </div>
          </div>
          <div id="carousel-3" class="carousel-item white-text" href="#!">
            <div class="primary-overlay">
                <div class="container">
                    <h3 class="carousel-head">Third Panel</h3>
                    <p class="white-text">This is your third panel</p>
                </div>
            </div>
          </div>
          <div id="carousel-4" class="carousel-item white-text" href="#!">
            <div class="primary-overlay">
                <div class="container">
                    <h3 class="carousel-head">Fourth Panel</h3>
                    <p class="white-text">This is your fourth panel</p>
                </div>
            </div>
          </div>
    </div>

    <!-- Section: Icon Boxes -->
    <section class="section section-icons grey darken-2">
        <div class="container">
            <div class="row">
                <div class="col s10 offset-s1 m4">
                    <div class="card small hoverable">
                        <div class="card-content grey-text text-darken-3">
                            <div class="center"><i id="cards-icon" class="material-icons large deep-orange-text">style</i></div>
                            <h4>For Leagues:</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, quidem!</p>
                        </div>
                    </div>
                </div>
                <div class="col s10 offset-s1 m4">
                    <div class="card small hoverable">
                        <div class="card-content grey-text text-darken-3">
                            <div class="center"><i class="material-icons large deep-orange-text">store</i></div>
                            <h4>For Venues:</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, quidem!</p>
                        </div>
                    </div>
                </div>
                <div class="col s10 offset-s1 m4">
                    <div class="card small hoverable">
                        <div class="card-content grey-text text-darken-3">
                            <div class="center"><i class="material-icons large deep-orange-text">groups</i></div>
                            <h4>For Members:</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, quidem!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="parallax-container" style="height: 400px;">
        <div class="parallax parallax-1"><img src="{% static 'images/LB_landing1.jpg'%}"></div>
    </div>

    <!-- Section: Features - Leagues -->
    <section id="Leagues" class="section section-features-leagues grey darken-4 grey-text text-lighten-2 scrollspy">
        <div class="container">
            <div class="row" style="display: flex;">
                <style>
                    .feature-image {
                        background-image: url('{% static "images/Leagues-about.jpg" %}');
                    }
                </style>
                <div class="col l5 hide-on-med-and-down feature-image" style="border-radius: 10%;">

                </div>
                <div class="col s12 m12 l6 offset-l1">
                    <i class="material-icons medium deep-orange-text" style="display: inline-flex; vertical-align: middle;">vpn_key</i>
                    <span class="feature-title" style="font-size: 2.0rem; vertical-align: middle;"> League Solutions</span>
                    <h5>Running a business is ultimately about freedom.</h5>
                    <p>Turnkey league management services take care of the most difficult tasks running your league, and let you focus on your clients and members</p>
                    <ul id="league-collapsible" class="collapsible">
                        <li>
                          <div class="collapsible-header grey-text text-darken-3"><i class="material-icons">filter_drama</i>First</div>
                          <div class="collapsible-body"><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis recusandae velit dicta vero natus aspernatur, fuga provident possimus aliquid iste.</span></div>
                        </li>
                        <li>
                          <div class="collapsible-header grey-text text-darken-3"><i class="material-icons">place</i>Second</div>
                          <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                        </li>
                        <li>
                          <div class="collapsible-header grey-text text-darken-3"><i class="material-icons">whatshot</i>Third</div>
                          <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
                        </li>
                      </ul>
                </div>
            </div>
        </div>
    </section>

    {% endblock %}

    {% block script_block %}
    {{block.super}}
    <script>
        $(document).ready(function() {

            // Init Sidenav
            $('.sidenav').sidenav();

            // Init Carousel
            $('.carousel').carousel({
                fullWidth: true,
                indicators: true,
            });

            //Announcement Bar close
            $('#notification-close').click(function() {
                $('.notification-bar').fadeOut();
            });


            // Parallax
            $('.parallax').parallax();

            // Init collapsibles
            $('#league-collapsible').collapsible();

            // Init Login Modal
            $('#login-modal').modal();

            //Init Scrollspy
            $('.scrollspy').scrollSpy();

        });

        $('.sidenav li').click(() => {
            $('.sidenav').sidenav('close');
        })

        // Imitate scrollFire to close the announcement bar

        $(window).scroll(function() {
            if ($(this).scrollTop() > 0) {
                $('.notification-bar').hide();
            }
        });

        // Autoplay carousel / stop on hover / start on mouseleave
        var intervalId = setInterval(()=> {
            instance = M.Carousel.getInstance($('.carousel'));
            instance.next();
        }, 5000);

        $('.carousel').hover(() => {
            clearInterval(intervalId)
        });

        $('.carousel').mouseleave(() => {
            intervalId = setInterval(()=> {
                instance = M.Carousel.getInstance($('.carousel'));
                instance.next();
            }, 5000);
        });

        $('.carousel').on('touchstart', () => {
            clearInterval(intervalId)
        });

        $('.carousel').on('touchend', () => {
            intervalId = setInterval(()=> {
                instance = M.Carousel.getInstance($('.carousel'));
                instance.next();
            }, 5000);
        });

        $('#fixedCarouselButton').click(() => {
            var target = getCarouselHref();
            console.log(target)
            window.location.href = target;
        })

        var getCarouselHref = function() {
            return $('.carousel-item.active').attr('href')
        };

        $('.collapsible').click(function() {
            console.log('header clicked')
            setTimeout(function() {
                console.log($(this).children('li'))
            }, 1000)

        });




        function openLoginModal() {
            var instance = M.Modal.getInstance(document.getElementById('login-modal'));
            instance.open();
        };
    </script>
    {% endblock %}

templates/m_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/main_m.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block extrahead %}
    {% endblock %}
    {% block css_block %}
    {% endblock %}
</head>
<body>
    {% include "m_header.html" %}
    {% block body_block  %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block extra_body %}
    {% endblock %}
    {% include "m_footer.html" %}

    {% block script_block %}
    {{block.super}}
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script>
        $(document).ready(function() {
            // Get year
            var d = new Date();
            var n = d.getFullYear();
            $('#year').text(n)
        });
    </script>
    {% endblock %}
</body>
</html>

templates/m_footer.html
<!-- Footer -->
    <footer class="page-footer grey darken-3">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="white-text">Footer Content</h5>
              <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="white-text">Links</h5>
              <ul>
                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright grey darken-4">
          <div class="container">
          &copy; <span id="year"></span> LeagueBox
          </div>
        </div>
    </footer>

templates/m_header.html
{% load static %}
    <!-- Header -->
    <header class="main-header">

        <div class="navbar-fixed">
            <!-- Announcement Bar -->
            <div class="deep-orange">
                <div class="container">
                    <div class="notification-bar white-text center">
                        <strong>This service is in BETA</strong>
                        <div id="notification-close" class="right"><i class="material-icons">close</i></div>
                    </div>
                </div>
            </div>
            <nav class="grey darken-3">
                <div class="container">
                    <div class="nav-wrapper">
                            <a href="#" class="brand-logo logo">
                                    <img class="responsive-img" src="{% static 'images/leaguebox-logo-light.png' %}" >
                            </a>
                            <a href="#" data-target="mobile-nav" class="sidenav-trigger">
                                <i class="material-icons">menu</i>
                            </a>
                        <ul class="right hide-on-med-and-down">
                            {% if not user.is_authenticated %}
                            <li><a href="#Leagues">Leagues</a></li>
                            <li><a href="#!">Venues</a></li>
                            <li><a href="#!">Members</a></li>
                            <li><a onclick="openLoginModal()" class="btn waves-effect waves-light deep-orange modal-trigger">Login</a></li>
                            <li><a href="{% url 'App_Login:signup' %}" class="btn waves-effect waves-light grey darken-1">Sign Up</a></li>
                            {% else %}
                            <li><a href="{% url 'account_logout' %}" class="btn waves-effect waves-light grey darken-1">Log Out</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <style>
            .sidenav .background {
                background-image: url('{% static "images/Suited-Poker-Table-Felt-Black.jpg" %}');
            }
        </style>
        <ul class="sidenav" id="mobile-nav">
            <li>
                <div class="background">
                    <div class="logo-wrapper">
                        <img src="{% static 'images/leaguebox-logo-light.png' %}" >
                    </div>
                </div>
            </li>
            {% if not user.is_authenticated %}
            <li><a href="#Leagues">Leagues</a></li>
            <li><a href="#!">Venues</a></li>
            <li><a href="#!">Members</a></li>
            <li><a onclick="openLoginModal()" class="btn waves-effect waves-light deep-orange modal-trigger">Login</a></li>
            <li><a href="{% url 'App_Login:signup' %}" class="btn waves-effect waves-light grey darken-1">Sign Up</a></li>
            {% else %}
            <li><a href="{% url 'account_logout' %}" class="btn waves-effect waves-light grey darken-1">Log Out</a></li>
            {% endif %}
        </ul>
    </header>


    <!--Modal: Login -->
    <div id="login-modal" class="modal">
        <div class="modal-content">
            <h4>Account Login</h4>
            <form id="form-login-modal" action="{% url 'App_Login:login' %}" method="POST">
                {% csrf_token %}
                <div class="input-field">
                    <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="254" class="textinput textInput" required="" id="id_username">
                    <label for="username">Email</label>
                </div>
                <div class="input-field">
                    <input type="password" name="password" autocomplete="current-password" class="textinput textInput form-control" required="" id="id_password"
                    >
                    <label for="password">Password</label>
                </div>

        </div>
        <div class="modal-footer">
            <a href="{% url 'account_reset_password' %}" class="modal-action modal-close btn grey darken-1"><i class="material-icons modal-icon">password</i>&nbsp; Reset Password</a>
            <a id="login-submit" class="modal-action modal-close btn deep-orange"><i class="material-icons modal-icon">login</i>&nbsp; Login</a>
        </form>
        </div>
    </div>

    <!--Modal must be initialized in main template after materialize and jquery js loaded -->
    <!-- <script>
        $(document).ready(function() {

            // Init Login Modal
            $('#login-modal').modal();

        });

        function openLoginModal() {
            var instance = M.Modal.getInstance(document.getElementById('login-modal'));
            instance.open();
        };

    </script> -->

    <script>
        document.getElementById('login-submit').addEventListener('click', () => {
           console.log('clicked login')
           document.getElementById("form-login-modal").submit();
        });
    </script>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-dark bg-dark justify-content-between">
    <div class="container-fluid">
        <div class="navbar-nav">            
            <span>
                <a class="text-decoration-none" href="{% url 'App_Organization:home' %}">
                <img class="" src="{% static 'images/leaguebox-type-logo.png' %}" width="50px " height="50px" alt="">
                <img class="" src="{% static 'images/leaguebox-type-light.png' %}" width="150px" alt="">
                </a>
            </span>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item">
                <span onclick="openNav()"><i class="fa fa-bars fa-2x" style="color: #eee; cursor: pointer;"></i></span>
            </li>
        </ul>

    </div>
</nav>